instruments:
  virACQ:
    driver: sqdtoolz.Drivers.dummyACQ
    type: DummyACQ
  virACQblowup:
    driver: sqdtoolz.Drivers.dummyACQ
    type: DummyACQ
    init:
      blow_up_path: 'test_save_dir/blowup.txt'
  virDDG:
    driver: sqdtoolz.Drivers.dummyDDG
    type: DummyDDG
  virAWG:
    driver: sqdtoolz.Drivers.dummyAWG
    type: DummyAWG
  virMWS:
    driver: sqdtoolz.Drivers.dummyGENmwSource
    type: DummyGENmwSrc
  virMWS2:
    driver: sqdtoolz.Drivers.dummyGENmwSource
    type: DummyGENmwSrc